name: Generate Snake Game

on:
  schedule: # run automatically every 24 hours
    - cron: "0 0 * * *"
  workflow_dispatch: # allow manual runs
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate snake
        uses: Platane/snk@v3
        with:
          github_user_name: KARRITEJA555
          outputs: dist/snake.svg

      - name: Push generated snake.svg
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "Generate snake animation"
          add: "dist/snake.svg"
